version: '3.9'
networks:
  codeigniter:
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'postytwo-php'
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    networks:
      - codeigniter
  codeigniter:
      image: docker.io/bitnami/codeigniter:4
      container_name: 'postytwo-ci'
      environment:
        - CI_ENVIRONMENT=development
        - APP_BASE_URL=https://localhost/
        - ALLOW_EMPTY_PASSWORD=yes
        - CODEIGNITER_DATABASE_HOST=mssql
        - CODEIGNITER_DATABASE_PORT_NUMBER=1433
        - CODEIGNITER_DATABASE_USER=sa
        - CODEIGNITER_DATABASE_NAME=db_posty
        - CODEIGNITER_DATABASE_PASSWORD=Password!123
      ports:
        - 80:80
      links:
        - mssql
      volumes:
        - ./app:/var/www/html
      networks:
        - codeigniter
  nginx:
    image: nginx:stable-alpine
    container_name: 'postytwo-nginx'
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - codeigniter
  mssql:
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    container_name: postytwo-mssql
    environment:
        - MSSQL_SA_PASSWORD=Password!123
        - ACCEPT_EULA=Y
        - MSSQL_DATA_DIR=/var/lib/mssql/data
    ports:
        - '1433:1433'
    volumes:
        - './db:/var/lib/mssql'
    networks:
      - codeigniter
