version: '3.9'
networks:
  codeigniter:
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'posty-php'
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    networks:
      - codeigniter
  codeigniter:
      image: docker.io/bitnami/codeigniter:4
      container_name: 'posty-ci'
      environment:
        - CI_ENVIRONMENT=development
        - APP_BASE_URL=https://localhost/
        - ALLOW_EMPTY_PASSWORD=yes
        - CODEIGNITER_DATABASE_HOST=postgres
        - CODEIGNITER_DATABASE_PORT_NUMBER=5432
        - CODEIGNITER_DATABASE_USER=root
        - CODEIGNITER_DATABASE_NAME=db_posty
        - CODEIGNITER_DATABASE_PASSWORD=password!
      ports:
        - 80:80
      links:
        - postgres
      volumes:
        - ./app:/var/www/html
      networks:
        - codeigniter
  nginx:
    image: nginx:stable-alpine
    container_name: 'posty-nginx'
    ports:
      - '8081:80'
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - codeigniter
  postgres:
    image: postgres
    container_name: posty-postgresql
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password!
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/db:/docker-entrypoint-initdb.d
    networks:
      - codeigniter
